### ISSUE TITLE
Support `--files` parameter

### ISSUE THREAD

**Issue by marandaneto** [domohuhn/mutation-test#19]
Similar to https://github.com/muter-mutation-testing/muter#muter-can-be-run-in-your-ci

Mutation tests are usually slow to run, I'd like to test only the modified files in my PR via CI.

**Comment by domohuhn** [comment]
This is technically already possible. You can provide a list of files as arguments, but you would have to add a custom rule file as input:
`mutation_test -b --rules cfg.xml <file1> <file2> <file3> ...`
The content of `cfg.xml` has to be:
```
<?xml version="1.0" encoding="UTF-8"?>
<mutations version="1.0">
  <commands>
    <command>dart test</command>
  </commands>
</mutations>
```
I understand that it is inconvenient that you have to provide the test command in an xml file. Another problem right now is that you get a report file for each of the input files instead of a single report. These issues can be solved.

What would you expect as return value? Should mutation_test give a nonzero return value if any test fails?

**Comment by marandaneto** [comment]
I'd stick to the current behavior, the difference is that instead of using the current folder, you use the given files, still a single report, same return value.

**Comment by domohuhn** [comment]
This ticket is obsolete with version 1.5.0. Even though there is no files parameter, you can list the files to analyse separated by spaces when invoking the program.

See https://github.com/domohuhn/mutation-test#running-an-incremental-analysis-ci
