### ISSUE TITLE
Generating mutants only for the code that is covered by test suites

### ISSUE THREAD

**Issue by mahmuttaskiran** [domohuhn/mutation-test#24]
We are trying to run a mutation test for our project daily nightly. The estimated time to complete the test shown by the tool is ~21h 12m 17s, which makes it hard to run the mutation test for the whole project.

As far as I understood, this tool generates the mutants for the code regardless of whether the test suites cover it. If so, it will be better to generate mutants only for the code covered by the test suites. 

I'd also like to know how mutants are subjected to test suites. Is every mutant subjected to the whole test suite or only the test that covers the mutant itself?

**Comment by domohuhn** [comment]
Correct, currently the code coverage is not taken into account. If coverage data can be generated by the test tool (or provided as argument when calling the program), then all code that is never executed could be marked and the verification step can be skipped. Adding this functionality is a bit of work but it should be possible. I guess the lcov coverage file format is not too complicated.

For your second question: Every mutant is tested against all test suites or test commands. Running only the matching tests is problematic - mutating the code might change the paths taken during the test cases, and then the selected tests based on the coverage may be wrong. Adding this functionality would also dramatically increase the complexity of this program:

1. a first pass would have to discover all tests
2. the next pass has to collect the coverage information for every test suite
3. for every mutant a set of test suites has to be created

If you want to reduce the time the analysis takes, you can either do an incremental analysis based on the diff between two commits, or you can create several configuration files instead of using the automatic discovery. For example, if the project is split into several modules and each module has its own test suites, then you could create configurations for each module that define the input files ( and lines for each file ) and the test commands.

**Comment by mahmuttaskiran** [comment]
Thank you for the details and such a good tool. As you suggested, we are considering only running mutation tests for PR's diff and modules.

**Comment by domohuhn** [comment]
I have added the --coverage switch in version 1.6. You can now reduce the number of mutations by providing the coverage information. See also https://github.com/domohuhn/mutation-test#speeding-up-the-analysis
